<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="LAP-TZD-0X74796" name="ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18" tests="3" failures="0" timestamp="2020-02-03T14:53:15 IST" time="3.129" errors="1">
  <testcase name="prepareRemittance" time="3.129" classname="ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.util.Objects.requireNonNull(Unknown Source)
at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:106)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:85)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:45)
at ocean.common.Keywords.click(Keywords.java:31)
at ocean.common.CommonFunctions.goToUnderWritingTab(CommonFunctions.java:292)
at ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18.prepareRemittance(OCEAN_Pricing_TC_05To14_18.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- prepareRemittance -->
  <testcase name="validatePremiumCalculationForDealerAsPrimaryAccount" time="0.000" classname="ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18">
    <skipped/>
  </testcase> <!-- validatePremiumCalculationForDealerAsPrimaryAccount -->
  <testcase name="validatePremiumCalculationForDealerAsPrimaryAccount" time="0.000" classname="ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18">
    <skipped/>
  </testcase> <!-- validatePremiumCalculationForDealerAsPrimaryAccount -->
</testsuite> <!-- ocean.test.condition.pricing.OCEAN_Pricing_TC_05To14_18 -->
